### ISSUE TITLE
Inefficient code in clean_data function in run.py

### ISSUE THREAD

**Issue by mauliknshah** [dsp-uga/Project-1-Naive-Bayes-classification#2]
The striping and removing stop words part uses the for loop, which is very inefficient. 

I used the below code in the project-0 in Scala: 
 val stopWords = spark.textFile("stopwords/stopwords.txt").map(_.toLowerCase())
 val stopWordsSet = stopWords.collect().toSet
 //Filtered List by removing the stopwords and take the top 40 again.
val stopWordFiltered = spark.parallelize(wordCountFiltered.filter(word => !stopWordsSet.contains(word._1)).take(40))

Please update the python code to remove overheads.

**Comment by raun1** [comment]
All is fine but you are using ".collect()" which  can actually be averted by simply using filter 
X_train.map(lambda x:x.split(" ")).filter(lambda x:x not in stopwords)
.map(lambda x:[xx+" " for xx in x])
This last step should merge back the tokens back into a single line, But i didnt do that ever so cant guarantee.
The reason I did the filter stop words in a udf is because I am splitting the mapping of X_train's to y_train 
- eg - X_train[i] = "hello" y_train[i]= "mcat","ccat". We need to duplicate hello twice.
So while doing that I used a loop and hence i decided to do the filter stopwords there itself instead of having another extra operation.
But I am sure some kind of join takes care of this duplication issue. I didnt check those yet. If you can check and find out I will update that section.
